# Generated by Django 4.0.6 on 2022-12-11 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz', models.CharField(help_text='Informe o nome da matriz', max_length=20)),
                ('reprodutor', models.CharField(help_text='Informe o nome do reprodutor', max_length=20)),
                ('parto', models.CharField(choices=[('Simples', 'Simples'), ('Duplo', 'Duplo'), ('Triplo', 'Triplo')], max_length=10)),
                ('data_de_nascimento', models.DateField(help_text='Por favor use o formato: <em>DD-MM-AAAA</em>.', verbose_name='Data de parição')),
                ('habilidade_materna', models.CharField(choices=[('Bom', 'Bom'), ('Regular', 'Regular'), ('Ruim', 'Ruim')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_spending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
