# Generated by Django 4.0.6 on 2022-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='data_de_nascimento',
            field=models.DateField(help_text='Por favor use o formato: <em>DD/MM/AAAA</em>.', verbose_name='Data de parição'),
        ),
    ]
